#!/bin/sh
#TODO mv old if not already there, localmodconfig, then diff
cd /usr/src/linux
diff --changed-group-format="%>" --unchanged-group-format="" .config-old .config | tee -a /etc/kernel/config.d/x240-kernel.config
